{
 "title": "PoolMaster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "pH & Orp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "pH" }
   ],
   "targets": [
    {
     "alias": "pH",
     "measurement": "PoolMaster",
     "query": "SELECT mean(\"pH\")  / 100 FROM \"PoolMaster\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Orp",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "Orp" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Chl Pump",
     "measurement": "PoolMaster",
     "query": "SELECT \"FiltState\" *7.5 FROM \"PoolMaster\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ChlPumpState" ], "type": "field" },
       { "params": [ "*7.5" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "pH Pump",
     "measurement": "PoolMaster",
     "query": "SELECT \"FiltState\" *7.5 FROM \"PoolMaster\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pHPumpState" ], "type": "field" },
       { "params": [ "*7.5" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Orp setpoint",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "OrpSP" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "pH setpoint",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "pHSP" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "targets": [
    {
     "alias": "Water temp.",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "Tmp" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 4 },
   "targets": [
    {
     "alias": "Orp",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "Orp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 8 },
   "targets": [
    {
     "alias": "pH",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water pressure & temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Pressure (bar)" }
   ],
   "targets": [
    {
     "alias": "Pressure",
     "measurement": "PoolMaster",
     "query": "SELECT mean(\"PSI\")  / 100 FROM \"PoolMaster\" WHERE $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "PSI" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "Tmp" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Filtration",
     "measurement": "PoolMaster",
     "query": "SELECT \"FiltState\" FROM \"PoolMaster\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "FiltState" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Water setpoint",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "WSP" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mode",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "AutoMode" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filtration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "FiltState" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "WaterHeat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chl pump uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 17 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "ChlUpT" ], "type": "field" },
       { "params": [ "/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "pH pump uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 17 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "PhUpT" ], "type": "field" },
       { "params": [ "/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tank levels",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 17 },
   "targets": [
    {
     "alias": "ChlTank",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "ChlF" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "AcidTank",
     "measurement": "PoolMaster",
     "select": [
      [
       { "params": [ "AcidF" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}